apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: deploy-phpmyadmin
  namespace: shared-services
  labels:
    app: label-deploy-phpmyadmin
spec:
  selector:
    matchLabels:
      app: label-backend-deploy-phpmyadmin
      tier: label-backend-deploy-phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: label-backend-deploy-phpmyadmin
        tier: label-backend-deploy-phpmyadmin
    spec:
      containers:
      - image: bitnami/phpmyadmin:latest
        name: phpmyadmin
        ports:
        - containerPort: 80
          name: phpmyadmin
