apiVersion: v1
kind: Pod
metadata:
  name: jumpod-ubuntu
  namespace: default
spec:
  containers:
  - name: jumpod-ubuntu
    image: ubuntu:20.04
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always